// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDss8a8BALfIixIOtAVxfIQbOuUgrewk7A',
    appId: '1:1027939717185:web:5e2a3a8b4ac92c2f5b36c0',
    messagingSenderId: '1027939717185',
    projectId: 'contactapp-e56c8',
    authDomain: 'contactapp-e56c8.firebaseapp.com',
    storageBucket: 'contactapp-e56c8.firebasestorage.app',
    measurementId: 'G-91YMFQ3BTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHiFLBmjlbdh7AMi68bRfAQ2377NFc0M',
    appId: '1:1027939717185:android:e87afda119a16b4c5b36c0',
    messagingSenderId: '1027939717185',
    projectId: 'contactapp-e56c8',
    storageBucket: 'contactapp-e56c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilUqSqG0keMRmXxjSNrM6uMSgYQPVqv0',
    appId: '1:1027939717185:ios:75e6418c081838b55b36c0',
    messagingSenderId: '1027939717185',
    projectId: 'contactapp-e56c8',
    storageBucket: 'contactapp-e56c8.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilUqSqG0keMRmXxjSNrM6uMSgYQPVqv0',
    appId: '1:1027939717185:ios:75e6418c081838b55b36c0',
    messagingSenderId: '1027939717185',
    projectId: 'contactapp-e56c8',
    storageBucket: 'contactapp-e56c8.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDss8a8BALfIixIOtAVxfIQbOuUgrewk7A',
    appId: '1:1027939717185:web:e114327d19c034055b36c0',
    messagingSenderId: '1027939717185',
    projectId: 'contactapp-e56c8',
    authDomain: 'contactapp-e56c8.firebaseapp.com',
    storageBucket: 'contactapp-e56c8.firebasestorage.app',
    measurementId: 'G-TNS08N977M',
  );
}
